# Generated by Django 3.2.6 on 2021-08-27 13:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='albumimage',
            name='album',
            field=models.ForeignKey(db_column='album_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.album', verbose_name='фотоальбом'),
        ),
    ]
